{"name":"SalesData","description":"","version":"1.0","culture":"it-IT","modifiedTime":"2021-01-11T19:47:57.5936589+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Customer":{"queryId":"d04d4497-0312-4ee9-a2e1-797c54310d47","queryName":"Customer","loadEnabled":true},"Product":{"queryId":"082ecc34-a166-4729-8e38-1d8dadb770a8","queryName":"Product","loadEnabled":true},"Sales":{"queryId":"da7b4306-4fda-43ca-a66d-c63c64595aeb","queryName":"Sales","loadEnabled":true}},"document":"section Section1;\r\nshared Customer = let\r\n  Origine = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/marcopozzan/Dati/master/PBI_Course_Customers.csv\"), [Delimiter = \",\", Columns = 15, Encoding = 65001, QuoteStyle = QuoteStyle.None]),\r\n  #\"Intestazioni alzate di livello\" = Table.PromoteHeaders(Origine, [PromoteAllScalars = true]),\r\n  #\"Tipo di colonna modificato\" = Table.TransformColumnTypes(#\"Intestazioni alzate di livello\", {{\"CustomerId\", Int64.Type}, {\"FirstName\", type text}, {\"LastName\", type text}, {\"Company\", type text}, {\"EmailAddress\", type text}, {\"WorkPhone\", type text}, {\"HomePhone\", type text}, {\"Address\", type text}, {\"City\", type text}, {\"State\", type text}, {\"Zipcode\", Int64.Type}, {\"Gender\", type text}, {\"BirthDate\", type text}, {\"FirstPurchaseDate\", type text}, {\"LastPurchaseDate\", type text}}),\r\n  #\"Scelta colonne\" = Table.SelectColumns(#\"Tipo di colonna modificato\", {\"CustomerId\", \"FirstName\", \"LastName\", \"Address\", \"City\", \"State\", \"Zipcode\", \"Gender\", \"BirthDate\", \"FirstPurchaseDate\", \"LastPurchaseDate\"}),\r\n  #\"Colonne di valori sottoposti a merge\" = Table.CombineColumns(#\"Scelta colonne\", {\"FirstName\", \"LastName\"}, Combiner.CombineTextByDelimiter(\" \", QuoteStyle.None), \"Customer\"),\r\n  #\"Rimpiazza M con Male\" = Table.ReplaceValue(#\"Colonne di valori sottoposti a merge\", \"M\", \"Male\", Replacer.ReplaceText, {\"Gender\"}),\r\n  #\"Rimpiazza F con Female\" = Table.ReplaceValue(#\"Rimpiazza M con Male\", \"F\", \"Female\", Replacer.ReplaceText, {\"Gender\"}),\r\n  #\"Dividi colonna in base al delimitatore\" = Table.SplitColumn(#\"Rimpiazza F con Female\", \"BirthDate\", Splitter.SplitTextByDelimiter(\" \"), {\"BirthDate.1\", \"BirthDate.2\"}),\r\n  #\"Colonne rimosse\" = Table.RemoveColumns(#\"Dividi colonna in base al delimitatore\", {\"BirthDate.2\"}),\r\n  #\"Modificato tipo di colonna con impostazioni locali\" = Table.TransformColumnTypes(#\"Colonne rimosse\", {{\"BirthDate.1\", type date}}, \"en-US\"),\r\n  #\"Colonne rinominate\" = Table.RenameColumns(#\"Modificato tipo di colonna con impostazioni locali\", {{\"BirthDate.1\", \"BirthDate\"}})\r\nin\r\n  #\"Colonne rinominate\";\r\nshared Product = let\r\n  Origine = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/marcopozzan/Dati/master/PBI_Course_Products.csv\"), [Delimiter = \",\", Columns = 11, Encoding = 65001, QuoteStyle = QuoteStyle.None]),\r\n  #\"Intestazioni alzate di livello\" = Table.PromoteHeaders(Origine, [PromoteAllScalars = true]),\r\n  #\"Modificato tipo di colonna con impostazioni locali\" = Table.TransformColumnTypes(#\"Intestazioni alzate di livello\", {{\"UnitCost\", Currency.Type}}, \"en-US\"),\r\n  #\"Modificato tipo di colonna con impostazioni locali 1\" = Table.TransformColumnTypes(#\"Modificato tipo di colonna con impostazioni locali\", {{\"ListPrice\", Currency.Type}}, \"en-US\"),\r\n  #\"Tipo di colonna modificato\" = Table.TransformColumnTypes(#\"Modificato tipo di colonna con impostazioni locali 1\", {{\"ProductId\", Int64.Type}, {\"ProductCode\", type text}, {\"Title\", type text}, {\"Description\", type text}, {\"ProductCategory\", type text}, {\"UnitCost\", Int64.Type}, {\"ListPrice\", Int64.Type}, {\"Color\", type text}, {\"MinimumAge\", Int64.Type}, {\"MaximumAge\", Int64.Type}, {\"ProductImageUrl\", type text}}),\r\n  #\"Colonne rinominate\" = Table.RenameColumns(#\"Tipo di colonna modificato\", {{\"Title\", \"Product\"}}),\r\n  #\"Dividi colonna in base al delimitatore\" = Table.SplitColumn(#\"Colonne rinominate\", \"ProductCategory\", Splitter.SplitTextByDelimiter(\" > \"), {\"ProductCategory.1\", \"ProductCategory.2\"}),\r\n  #\"Colonne rinominate 1\" = Table.RenameColumns(#\"Dividi colonna in base al delimitatore\", {{\"ProductCategory.1\", \"Category\"}, {\"ProductCategory.2\", \"SubCategory\"}})\r\nin\r\n  #\"Colonne rinominate 1\";\r\nshared Sales = let\r\n  Origine = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/marcopozzan/Dati/master/PBI_Course_InvoiceDetails.csv\"), [Delimiter = \";\", Columns = 6, Encoding = 65001, QuoteStyle = QuoteStyle.None]),\r\n  #\"Intestazioni alzate di livello\" = Table.PromoteHeaders(Origine, [PromoteAllScalars = true]),\r\n  #\"Modificato tipo di colonna con impostazioni locali\" = Table.TransformColumnTypes(#\"Intestazioni alzate di livello\", {{\"InvoiceDate\", type date}}, \"en-US\"),\r\n  #\"Tipo di colonna modificato\" = Table.TransformColumnTypes(#\"Modificato tipo di colonna con impostazioni locali\", {{\"Id\", Int64.Type}, {\"Quantity\", Int64.Type}, {\"SalesAmount\", Int64.Type}, {\"InvoiceId\", Int64.Type}, {\"ProductId\", Int64.Type}, {\"InvoiceDate\", type text}}),\r\n  #\"Colonne rinominate\" = Table.RenameColumns(#\"Tipo di colonna modificato\", {{\"Id\", \"CustomerId\"}})\r\nin\r\n  #\"Colonne rinominate\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Customer","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Customer.csv"},"attributes":[{"name":"CustomerId","dataType":"int64"},{"name":"Customer","dataType":"string"},{"name":"Address","dataType":"string"},{"name":"City","dataType":"string"},{"name":"State","dataType":"string"},{"name":"Zipcode","dataType":"int64"},{"name":"Gender","dataType":"string"},{"name":"BirthDate","dataType":"date"},{"name":"FirstPurchaseDate","dataType":"string"},{"name":"LastPurchaseDate","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2021-01-11T20:04:42.2476827+00:00","location":"https://bootcamp2021.dfs.core.windows.net/powerbi/Dataflow/SalesData/Customer/Customer.csv.snapshots/Customer.csv@snapshot=2021-01-11T20:04:42.1348370Z"}]},{"$type":"LocalEntity","name":"Product","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Product.csv"},"attributes":[{"name":"ProductId","dataType":"int64"},{"name":"ProductCode","dataType":"string"},{"name":"Product","dataType":"string"},{"name":"Description","dataType":"string"},{"name":"Category","dataType":"string"},{"name":"SubCategory","dataType":"string"},{"name":"UnitCost","dataType":"int64"},{"name":"ListPrice","dataType":"int64"},{"name":"Color","dataType":"string"},{"name":"MinimumAge","dataType":"int64"},{"name":"MaximumAge","dataType":"int64"},{"name":"ProductImageUrl","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2021-01-11T20:04:39.423189+00:00","location":"https://bootcamp2021.dfs.core.windows.net/powerbi/Dataflow/SalesData/Product/Product.csv.snapshots/Product.csv@snapshot=2021-01-11T20:04:39.2831249Z"}]},{"$type":"LocalEntity","name":"Sales","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Sales.csv"},"attributes":[{"name":"CustomerId","dataType":"int64"},{"name":"Quantity","dataType":"int64"},{"name":"SalesAmount","dataType":"int64"},{"name":"InvoiceId","dataType":"int64"},{"name":"ProductId","dataType":"int64"},{"name":"InvoiceDate","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2021-01-11T20:04:44.9969032+00:00","location":"https://bootcamp2021.dfs.core.windows.net/powerbi/Dataflow/SalesData/Sales/Sales.csv.snapshots/Sales.csv@snapshot=2021-01-11T20:04:44.8768832Z"}]}]}